---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dragonfly
components:
  - ../components/common
  - ../components/repos/app-template
resources:
  - ./namespace.yaml
  - ./operator/ks.yaml
  - ./instances/ks.yaml
