apiVersion: v1
kind: Secret
metadata:
  name: grafana-env-sops
stringData:
  OAUTH_CLIENT_ID: ENC[AES256_GCM,data:3usWSWEhW1APibIx6CepA68ikS5fYoF1N0s+xAltKB7EgHyKQzpx0g==,iv:3iaxRaEejQj2CkdtEdZ1rFP05q3KHjqWNSFSxbihQP0=,tag:no3o2+EQkBwyT/mG2k5BUA==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:L+NmnlYzonmcjxnXY1Fx27Q+ZRTVR2lx8xJ1jGMDXelnh95vp9C/TrxTSaAloEMxRseFx2TLaeUGJ2RBs2gp4dTLpURq1wLIoap5rMUc++Tp0Z5mC9kHnNPGwRWFwk9OczhFx/4baMNqSpyVV+SrQSwqZwT6BscnIuwU/TR6E/Y=,iv:MmffddvKkUBYPYGXXB/eZwD3smV0VeTeO8Os5LgsUh8=,tag:FT6K0nZZH5kq5hx5OYQjwQ==,type:str]
sops:
  age:
    - recipient: age1r9x82vylxeu648374ysaydeawu0a2xankc3fclw060ps2cqrsucq4zwtd5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmY29POGRiTEpDZzZzc1l2
        V0k4em1KdlRtRUY0T2g1NS84b3JuaVowUXo0CnFHVlBPWTdLWEV5SENQT3RPNEx4
        blhxd3FpRTl4MlMrREFwK2lLR2ovUWcKLS0tIDZtVWVNM3hqNENoREV0K1preXA4
        d05ZVFRSRkxUWUVBMitHbURtWDlwRGcK2nfT/tLRxiuMFev8Quwsudj+dWBpcr3P
        /Z8B95l7CK+mihrPPKNFB6usB9sHZoNRVERzeb8aV1UrM41V3nr/rg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-05T06:10:49Z"
  mac: ENC[AES256_GCM,data:oHKV9pEbktUxwU3VdiS+FX21B8XMO680IcqU0kP0IF+jwJoO7LtI3GLvKMjehwtYW+DRZJQX7itrVqX0FMYywzZMfHOcPZKT1CB0IqWr5rlbGv6Vey+o1TPLIGT2pfrX+ap36SSAuga+PMRS362YeVgLwwBvXQ8Nc6HATORVETQ=,iv:/knDkpngzSL379UrXLagE2NYR1/LIZa2HWGJUzR3oeE=,tag:MwAre/hZGsy+AqBsQsiWRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
