apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-secret
  namespace: tailscale
type: Opaque
stringData:
  clientId: ENC[AES256_GCM,data:C8PaeE8GZxlKLVjH52HDcrA=,iv:cerS5S/1/CKSZ7DaRF1jxMciY2QlgA0lvCT2eY8lGp4=,tag:stXdCKXj3qFsDDF+pEEXQw==,type:str]
  clientSecret: ENC[AES256_GCM,data:XuDnyKLWIcDSmjZ1I2fsNiShOSlN9cFrCVzxUpbrnkfOTpqf0qHFAlXlGZlyA6rQ8H4eIzoZ2FpNMndsnKkMZQ==,iv:VjY0CfXPQgDwjOB96U/8Zq/GcwCsb9OiJt0WSY4Q/44=,tag:Ebykfngjnl83Olj+RPZ4pQ==,type:str]
sops:
  age:
    - recipient: age1r9x82vylxeu648374ysaydeawu0a2xankc3fclw060ps2cqrsucq4zwtd5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTjRqNWY5ZDZHRDhWYTdh
        ZDhYL2hDMlZXdU5hbkdpSGhuTG1JMDdvYVh3CmUrenVONW1TczVicTJmcUNET3Mz
        K0hmWjM2NlJUSU1vaDNSWWpHdXFTN0UKLS0tIDdlREo5Q3ZuMk14NHY1L1hacytV
        VFdEV0tDZ20zWVA0YWVqZS9UcllHa00KeFYzL5OdQ3QqEyG6dJSEW9bxCKMprXIj
        2mMoGLLdP4FM1ajDgVvTI8NZs6M79g3qJq9pTI9NBKpwj6nTnQkyeA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T18:01:16Z"
  mac: ENC[AES256_GCM,data:mZZJhiYGoHymXuShmQL91Pja2WDiiCE7w+yDOON39hiI5SkLY8IZFpZTjmbHuJ8vnF0j20Nil6GswDslazwsY9634dCUrq0aYbn1uF5V8RwKn10DTizgofbg8JOTbcCEJMd/rqIPeCuNtg5xz6sHMMyzJ3Mdan69+hWaINF0hLk=,iv:z8nLiylvIcHCqHy4PqKcWZaf2h4v/ehG5+cZFsmL8Xg=,tag:64qTPqKJvis9Hfqfs7oaaA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
