apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-cache-secret
  namespace: dragonfly
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:2yaatTvUbpoKPLP7GFI=,iv:FAP6ln1BbRvU8wBF61ZlC/zqay7+MIEruNr7mK+AHWA=,tag:y4IkbSByEm+C2fLls4MvEA==,type:str]
sops:
  age:
    - recipient: age1r9x82vylxeu648374ysaydeawu0a2xankc3fclw060ps2cqrsucq4zwtd5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ2JFdHFrQjN0ODBqNmRh
        K0xRVGxNem9rVkVidXRUSWFMdytvMm5RQ21RCk83QWJGcHdsVGcveERGVFRVdDFG
        U2ozSys1Y2VSTzlCa2YrbDIrakZGdFEKLS0tIHN1Ymtod3ZqR3ZaOVlrMmtlc3Bk
        RWZyT3FHVllTcWlUcEpoQjc3TjNPTDgKrsnGrRuFOBKp98hPG6EZUiluF5sx927y
        7xpc6Vl9B6LNiAW1pLFX05nQHbQ+G1Clot59bCnOON3/LnGS6nZxNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T09:18:10Z"
  mac: ENC[AES256_GCM,data:kU8oDJ2EXaIOmoX671Dqe9oPa+EJa8Kx1f7JQ38rx2wfyeiQhh0kWftZY9W+mgTZ0G/Aiz1NVjxfV/05ZQj8GK8MuwK93V9QD342ogK9DEXIrtjtDIDXrMauFXXt0NGh8LfEUj1CQrDSn2Avj0b6sOCm50024KEFrvT/MLCZP0A=,iv:xm5l1fSbw/7t/oXaHEGUXjwXAuOzO6MYy5ypKMJ/7a4=,tag:fDChqoUfVqWz8VwvVhdEQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-ha-secret
  namespace: dragonfly
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:1u9tfSYZIo/6Z6GvqyA=,iv:XaIiR7cY7Bkxz2a3ug0YWxIwgzBB7cc917hOtkd8DlU=,tag:4sKzRSIBaR7kk+PQB1tINw==,type:str]
sops:
  age:
    - recipient: age1r9x82vylxeu648374ysaydeawu0a2xankc3fclw060ps2cqrsucq4zwtd5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ2JFdHFrQjN0ODBqNmRh
        K0xRVGxNem9rVkVidXRUSWFMdytvMm5RQ21RCk83QWJGcHdsVGcveERGVFRVdDFG
        U2ozSys1Y2VSTzlCa2YrbDIrakZGdFEKLS0tIHN1Ymtod3ZqR3ZaOVlrMmtlc3Bk
        RWZyT3FHVllTcWlUcEpoQjc3TjNPTDgKrsnGrRuFOBKp98hPG6EZUiluF5sx927y
        7xpc6Vl9B6LNiAW1pLFX05nQHbQ+G1Clot59bCnOON3/LnGS6nZxNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T09:18:10Z"
  mac: ENC[AES256_GCM,data:kU8oDJ2EXaIOmoX671Dqe9oPa+EJa8Kx1f7JQ38rx2wfyeiQhh0kWftZY9W+mgTZ0G/Aiz1NVjxfV/05ZQj8GK8MuwK93V9QD342ogK9DEXIrtjtDIDXrMauFXXt0NGh8LfEUj1CQrDSn2Avj0b6sOCm50024KEFrvT/MLCZP0A=,iv:xm5l1fSbw/7t/oXaHEGUXjwXAuOzO6MYy5ypKMJ/7a4=,tag:fDChqoUfVqWz8VwvVhdEQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
