apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:xq+9/FYXTy0Cz+E=,iv:sxs+bPM+Fl92Z+44N8Zw48+ezrOIwzr+Yxgx0jxbjpY=,tag:DPRYt4VmdY2hSHdyNp39uQ==,type:str]
  AUTH_SERVICE: ENC[AES256_GCM,data:7vK8wAdQyrAkUudjOgNYeg==,iv:0N8Qmz8J5cUtBGK2qci7U2EjyHly+CQNxvQbtYY3WY8=,tag:aaoMb1BDhbRAaMIOjkb9Ow==,type:str]
sops:
  age:
    - recipient: age1r9x82vylxeu648374ysaydeawu0a2xankc3fclw060ps2cqrsucq4zwtd5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQnhmRDRtQnFVQ3lKRG1F
        c0dtSnQzcXdRWHZ0dUFVRVFMOUpCSUpqR0g0CnhJNDlkL2lqbDZ3aXBWNzZZRkdH
        ZDZOV0RtQlFuSjVERkFUZVZGcTE5SVkKLS0tIGI2TjZXcFVtdlFZUmpCSVllSXZw
        V0Z2dStXUlVEcVUzNk5xMS9XUmZGZlUKfrKjuujxj1uwzvNkS3EnBRnUY2o5/++m
        OR6i4HANYWVsZ5gNCw98F/DwnwBP6aVKqCEnHmx/c6afRSfTq6LP7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-05T04:52:32Z"
  mac: ENC[AES256_GCM,data:x4aSmYhGt+yJVmus+pePFLTe1h7RaUON5OP2dF05zu7+2/TzFqZk20ccWrqG6HFh8WA/ONy0UMqdi2GNHogMWuONuayhypQje5KfOKMqg/b7QKE9ehQaOkglEDdrb3Drht7MNKP334TwlZcdV/f5EUcAwFGUFAwBpJQswejHaPM=,iv:FmrbK43qzfLW8MnhexKUt520aoG7Nk+p3d2AVpHHTGI=,tag:RN2JFT8Cs7A60ptmITOvmg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
