---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ai
  - ./cert-manager
  - ./database
  - ./default
  - ./external-services
  - ./flux-system
  - ./kube-system
  - ./monitoring
  - ./network
  - ./security
  - ./storage
