apiVersion: v1
kind: Secret
metadata:
  name: open-webui-env-sops
stringData:
  OAUTH_CLIENT_ID: ENC[AES256_GCM,data:5kUA9ADInapGzrfERdOHyrNrqPGbk/TNVce1m4H4VkynplFtOlD+CA==,iv:64Ax7kiAnmzaxPiF9456VBhyk3jZTEFye1p+7Xowd90=,tag:3RK+rjJC0CTujBrW+EGCgw==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:KbXdoDhPd2hTaOMdkJ62kllv9J9Ufvl7Yh6XKMz3ezhRCnQYSLBVao2p9iOQRTpMQWPxSwO7NvRtDHxRUS5IiiMphQ6eHFab9pa/4X+CC0bslsWwJlBryOfvSDHtAjWFWrqkkkCHmCtVhZxJDb3h7Z5/HX8er1kmR0k6OpGUkjWC,iv:kUnwC56MvLr5NYefvs5B+RVwlybqBPH59IKt/0+XWkw=,tag:WYoCAn8jHsyAdmt1KbtAsw==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:DNdv0ZXRDv0lHkKOlvA/YJgf0NxNOZDnLagMGeoZcLTRsAmQAOtRQTS7AZLmpYkVgVRVbej0NzQbEkEmtTBq/5LuW2RcEaAjTlOmANRm+9apGX59vXe/a6e5K33qWko7WDa6vfesKukJKJUvTBAdnvfgXTZRzZwGSWhtxxAvK4lNib+oZzxoNmPMWP8axQGce203d8hbx+AitLb8jOfyjPt08ApQSTg=,iv:LYsD4vXRssBRafepezX+25MTNGXkiYqatlnFJPxdo3s=,tag:B4Ny/T0peSUjCBw8dxwrlQ==,type:str]
sops:
  age:
    - recipient: age1r9x82vylxeu648374ysaydeawu0a2xankc3fclw060ps2cqrsucq4zwtd5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdzdDVnFBTFhhVlRyNmhW
        bU5Ic252THdzV1NEUzNIZ1VTekl5ejkrQm5nCnNuV2tibUo1QjdJbFRTTStJTWZM
        cUlvZ29LMndQOXQzQmpLMFhHUUxhTFUKLS0tIFhiZjFhVzRmYXdqOFhWdmp2dW9F
        UzI2MVZ5cnBwQ3NXYWVzcWU3Q2lsWGMKye5/xHiXNuhAgmNA/HBNge4vFG6tp3xQ
        78GAmOsV27pO3ax8W/l0KKEGrEAFfi8fPpxemU7WZJhyoZEBh7xhhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-05T02:27:31Z"
  mac: ENC[AES256_GCM,data:n8lTkf4P4ERhahEDuYu18e+wGR0ldn2ah2LhFnUPssWb7bApn9c7nYchzo/M0t7F+9UAFU9nL6q75mGsKnkMZr3caomMtJhjIUz2ohMJ/iQyVDZaLiW8Uymo8lwps07JHriaw4uzIxfYHN6U9+3jiWrOKIT8A1Zyl3AOyjp5VRQ=,iv:Z/kYBRW7zl7CqIBQ/AnDx4uVuZ3tJIzkb1jDWEgs2hE=,tag:mgn53QBXIqi3c6hngSeeVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
