# PostgreSQL credentials for Open-WebUI
# This secret will be used by CloudNativePG to create the database user
apiVersion: v1
kind: Secret
metadata:
  name: open-webui-postgres-app
  namespace: ai
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:GKvHQXkno5cC,iv:dk7Fb853PUlWddMefQW2n+mHCCPgSMQqq19cQ4C35dE=,tag:kJeMDyyTGb22bIsh/dfdzg==,type:str]
  password: ENC[AES256_GCM,data:tpWZyFR2hilWoJcAETGg2yOvVOXu65A=,iv:JqSw+xb+Vl8ag6L6witHd6aSqiaBK7xHOkoAzUjb9lA=,tag:kOEXsA5nYiOXx58dYkRXSQ==,type:str]
  postgresql: ENC[AES256_GCM,data:xUWjdrSFQrFjV8xwvQEngcTy0ES0gXbPO6FoqNVDrA6CmCK7eeEIB9G/eE6mcZujuppVzuVy3mw+X/+3XUsz15+TCGEya6OmVw==,iv:bEu3nqdMbsX7kBmm2hQkYtla3DPGAgVLmfxL5q+QPAk=,tag:hxMrelkSlUgVZwrueXBu0g==,type:str]
sops:
  age:
    - recipient: age1r9x82vylxeu648374ysaydeawu0a2xankc3fclw060ps2cqrsucq4zwtd5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SVdYamptS3M0Y0lKQThW
        aGRGK2dQZXVFK05rcURFOHE0a3dlKyt0YTFVCjJycjBMelhyWkY3dnR1eEp4cU04
        bjRRVVpESVA0STgwTDFhY21MY2FDSXMKLS0tIHlpdThPUU5zRFc3djZNUVJyQjFl
        RW9IejVXc2x5YnB3RkZHR29zbHdDT28KAnXSQ3oYZfMVNhEPBMw6Pky6w9wxHje6
        FXtR30tgMvb2mKIwzHLoVEoZkj7Y66NBoJqOkmQZ4ROCsYAbUa362g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-05T02:30:18Z"
  mac: ENC[AES256_GCM,data:dwQOklgPkevEHsMWkfRHypPLUTeLGoH0rC85eXqHdJcoxEyK75hslWAwXT8nT+9kwgpJ+PpArO7kLw1AibXqfOQHuu17JT9kbOwGM2xb5fCizt4wCNid0MEb2JU98wIrPqjuwJiNZn/7cEumQV3DPFezDJCZ5soUIwqpou4j5X4=,iv:ewgsF/wyzusPgw0nPaKBLBh/rAIXmH+KAwxT25Hyg2k=,tag:hGSjeD8L4F5SjP5pghRL8g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
